import {
  UserProfile,
  DepartmentData,
  JourneyRecord,
  ChallengeItem,
  RewardItem,
  UserRewardRecord,
  UtilityBillRecord,
  RecommendationItem,
  CampusBuildingHotspot,
} from './types';

export const INITIAL_USER_STUDENT: UserProfile = {
  uid: 'demo_student_101',
  email: 'chaitanya.student@coep.edu',
  name: 'Chaitanya Sharma',
  role: 'student',
  institutionId: 'inst_coep_01',
  institutionName: 'COEP Technological University',
  departmentId: 'dept_cse_01',
  departmentName: 'Computer Science & Engineering',
  studentId: 'CS2026-883',
  impactPoints: 2450,
  co2eAvoidedKg: 38.6,
  level: 3,
  levelName: 'Green Commuter',
  createdAt: '2026-08-15',
};

export const INITIAL_USER_ADMIN: UserProfile = {
  uid: 'demo_admin_202',
  email: 'sustainability.admin@coep.edu',
  name: 'Dr. Ananya Roy (Dean of Sustainability)',
  role: 'institution_admin',
  institutionId: 'inst_coep_01',
  institutionName: 'COEP Technological University',
  departmentId: 'dept_cse_01',
  departmentName: 'All Campus Departments',
  impactPoints: 12500,
  co2eAvoidedKg: 1420.5,
  level: 5,
  levelName: 'Carbon Guardian',
  createdAt: '2025-01-10',
};

export const INITIAL_DEPARTMENTS: DepartmentData[] = [
  {
    id: 'dept_cse_01',
    institutionId: 'inst_coep_01',
    name: 'Computer Science & Engineering',
    code: 'CSE',
    studentCount: 420,
    staffCount: 32,
    areaSqM: 4500,
    currentCo2eKg: 9800, // 9.8 t/month
    baselineCo2eKg: 11950,
    reductionPercent: 18.0,
    score: 92,
    breakdown: {
      electricityCo2eKg: 6076,
      computingCo2eKg: 1764,
      acCo2eKg: 882,
      transportCo2eKg: 588,
      generatorsCo2eKg: 294,
      foodCo2eKg: 196,
    },
    infrastructure: {
      buildings: 3,
      labs: 8,
      computers: 430,
      acUnits: 56,
      lights: 820,
      generators: 1,
      buses: 2,
    },
  },
  {
    id: 'dept_civil_02',
    institutionId: 'inst_coep_01',
    name: 'Civil & Environmental Engineering',
    code: 'CIVIL',
    studentCount: 380,
    staffCount: 28,
    areaSqM: 5200,
    currentCo2eKg: 11200,
    baselineCo2eKg: 13020,
    reductionPercent: 14.0,
    score: 86,
    breakdown: {
      electricityCo2eKg: 6944,
      computingCo2eKg: 1120,
      acCo2eKg: 1568,
      transportCo2eKg: 896,
      generatorsCo2eKg: 448,
      foodCo2eKg: 224,
    },
    infrastructure: {
      buildings: 2,
      labs: 6,
      computers: 180,
      acUnits: 42,
      lights: 650,
      generators: 1,
      buses: 2,
    },
  },
  {
    id: 'dept_etc_03',
    institutionId: 'inst_coep_01',
    name: 'Electronics & Telecommunication',
    code: 'E&TC',
    studentCount: 400,
    staffCount: 30,
    areaSqM: 4800,
    currentCo2eKg: 12400,
    baselineCo2eKg: 13770,
    reductionPercent: 10.0,
    score: 81,
    breakdown: {
      electricityCo2eKg: 7688,
      computingCo2eKg: 2232,
      acCo2eKg: 1240,
      transportCo2eKg: 620,
      generatorsCo2eKg: 372,
      foodCo2eKg: 248,
    },
    infrastructure: {
      buildings: 2,
      labs: 7,
      computers: 320,
      acUnits: 48,
      lights: 710,
      generators: 1,
      buses: 1,
    },
  },
  {
    id: 'dept_mech_04',
    institutionId: 'inst_coep_01',
    name: 'Mechanical & Production Engineering',
    code: 'MECH',
    studentCount: 450,
    staffCount: 36,
    areaSqM: 6100,
    currentCo2eKg: 13700,
    baselineCo2eKg: 14570,
    reductionPercent: 6.0,
    score: 74,
    breakdown: {
      electricityCo2eKg: 7535,
      computingCo2eKg: 1370,
      acCo2eKg: 1644,
      transportCo2eKg: 1370,
      generatorsCo2eKg: 1233,
      foodCo2eKg: 548,
    },
    infrastructure: {
      buildings: 4,
      labs: 10,
      computers: 240,
      acUnits: 38,
      lights: 950,
      generators: 2,
      buses: 3,
    },
  },
];

export const INITIAL_JOURNEYS: JourneyRecord[] = [
  {
    id: 'j_01',
    userId: 'demo_student_101',
    userName: 'Chaitanya Sharma',
    origin: 'Model Colony Hostel',
    destination: 'CSE Block 2',
    transportMode: 'walking',
    distanceKm: 2.4,
    durationMin: 28,
    actualCo2eKg: 0.0,
    alternativeCo2eKg: 0.312,
    avoidedCo2eKg: 0.312,
    impactPointsEarned: 31,
    verificationStatus: 'VERIFIED',
    timestamp: '2026-09-30 08:30 AM',
  },
  {
    id: 'j_02',
    userId: 'demo_student_101',
    userName: 'Chaitanya Sharma',
    origin: 'Campus North Gate',
    destination: 'Central Library',
    transportMode: 'cycling',
    distanceKm: 3.8,
    durationMin: 15,
    actualCo2eKg: 0.0,
    alternativeCo2eKg: 0.494,
    avoidedCo2eKg: 0.494,
    impactPointsEarned: 49,
    verificationStatus: 'VERIFIED',
    timestamp: '2026-09-29 04:15 PM',
  },
  {
    id: 'j_03',
    userId: 'demo_student_101',
    userName: 'Chaitanya Sharma',
    origin: 'Shivajinagar Station',
    destination: 'Main Campus Gate',
    transportMode: 'bus',
    distanceKm: 6.2,
    durationMin: 22,
    actualCo2eKg: 0.235,
    alternativeCo2eKg: 0.806,
    avoidedCo2eKg: 0.571,
    impactPointsEarned: 57,
    verificationStatus: 'VERIFIED',
    timestamp: '2026-09-28 09:10 AM',
  },
  {
    id: 'j_04',
    userId: 'user_priya_202',
    userName: 'Priya Verma',
    origin: 'Aundh Residence',
    destination: 'Civil Dept',
    transportMode: 'walking',
    distanceKm: 3.1,
    durationMin: 35,
    actualCo2eKg: 0.0,
    alternativeCo2eKg: 0.403,
    avoidedCo2eKg: 0.403,
    impactPointsEarned: 40,
    verificationStatus: 'VERIFIED',
    timestamp: '2026-09-30 09:00 AM',
  },
];

export const INITIAL_CHALLENGES: ChallengeItem[] = [
  {
    id: 'chal_walk_10k',
    title: 'Zero-Emission Commuter',
    description: 'Walk or cycle 10 km instead of using a motor vehicle.',
    category: 'transport',
    targetQuantity: 10,
    unit: 'km',
    rewardPoints: 150,
    co2eSavingKg: 1.3,
    currentProgress: 6.4,
    completed: false,
    expiresInDays: 4,
  },
  {
    id: 'chal_bus_3x',
    title: 'Transit Champion',
    description: 'Use the campus or public bus 3 times this week.',
    category: 'transport',
    targetQuantity: 3,
    unit: 'trips',
    rewardPoints: 100,
    co2eSavingKg: 1.8,
    currentProgress: 2,
    completed: false,
    expiresInDays: 3,
  },
  {
    id: 'chal_food_waste',
    title: 'Clean Plate Initiative',
    description: 'Log 5 consecutive days of zero meal food waste in campus mess.',
    category: 'food',
    targetQuantity: 5,
    unit: 'days',
    rewardPoints: 120,
    co2eSavingKg: 2.5,
    currentProgress: 5,
    completed: true,
    expiresInDays: 1,
  },
  {
    id: 'chal_lab_shutdown',
    title: 'Power Save Pioneer',
    description: 'Ensure lab PC shutdown at the end of daily computing sessions.',
    category: 'computing',
    targetQuantity: 4,
    unit: 'sessions',
    rewardPoints: 80,
    co2eSavingKg: 0.9,
    currentProgress: 3,
    completed: false,
    expiresInDays: 5,
  },
];

export const INITIAL_REWARDS: RewardItem[] = [
  {
    id: 'rew_canteen_20',
    title: '₹20 Campus Canteen Coupon',
    description: 'Valid at Central Canteen for coffee, snacks, or fruit juice.',
    merchant: 'COEP Central Canteen',
    pointsRequired: 500,
    category: 'canteen',
    icon: 'Coffee',
    couponCodePrefix: 'CAN20-',
  },
  {
    id: 'rew_library_print',
    title: 'Library Printing Discount Pass',
    description: 'Free 25-page laser printing at Central Library media desk.',
    merchant: 'University Library',
    pointsRequired: 750,
    category: 'printing',
    icon: 'Printer',
    couponCodePrefix: 'LIBPR-',
  },
  {
    id: 'rew_mess_pass',
    title: 'Special Organic Mess Pass',
    description: 'Complimentary healthy organic meal upgrade at Main Hostel Mess.',
    merchant: 'Campus Mess',
    pointsRequired: 1000,
    category: 'canteen',
    icon: 'Utensils',
    couponCodePrefix: 'MESS-',
  },
  {
    id: 'rew_cert',
    title: 'Sustainability Champion Certificate',
    description: 'Official Dean-endorsed digital & physical certificate of merit.',
    merchant: 'Dean of Student Affairs',
    pointsRequired: 2000,
    category: 'academic',
    icon: 'Award',
    couponCodePrefix: 'SUST-',
  },
];

export const INITIAL_USER_REWARDS: UserRewardRecord[] = [
  {
    id: 'urew_901',
    userId: 'demo_student_101',
    rewardId: 'rew_canteen_20',
    title: '₹20 Campus Canteen Coupon',
    merchant: 'COEP Central Canteen',
    couponCode: 'CAN20-8832-ECO',
    pointsSpent: 500,
    status: 'AVAILABLE',
    redeemedAt: '2026-09-25 11:20 AM',
  },
];

export const INITIAL_UTILITY_BILLS: UtilityBillRecord[] = [
  {
    id: 'bill_01',
    institutionId: 'inst_coep_01',
    departmentId: 'dept_cse_01',
    departmentName: 'Computer Science & Engineering',
    billingPeriod: 'September 2026',
    consumerNumber: 'ELE-400129-CSE',
    kwhConsumed: 18500,
    totalAmount: 148000,
    co2eKg: 15170, // 18500 * 0.82
    ocrStatus: 'VERIFIED',
    uploadedAt: '2026-09-28',
    notes: 'Approved after OCR verification by Dr. Ananya Roy.',
  },
  {
    id: 'bill_02',
    institutionId: 'inst_coep_01',
    departmentId: 'dept_civil_02',
    departmentName: 'Civil Engineering',
    billingPeriod: 'September 2026',
    consumerNumber: 'ELE-400130-CIV',
    kwhConsumed: 21100,
    totalAmount: 168800,
    co2eKg: 17302,
    ocrStatus: 'VERIFIED',
    uploadedAt: '2026-09-27',
  },
];

export const INITIAL_RECOMMENDATIONS: RecommendationItem[] = [
  {
    id: 'rec_01',
    targetType: 'department',
    targetName: 'CSE Department',
    title: 'High Nighttime Standby Electrical Drain',
    description: 'Laboratory computers and AC units remain powered after 9 PM. Automating lab PC shutdown saves ~420 kg CO2e monthly.',
    potentialSavingKg: 420,
    actionType: 'computing',
    confidence: 0.94,
    status: 'NEW',
  },
  {
    id: 'rec_02',
    targetType: 'institution',
    targetName: 'COEP Campus Bus Network',
    title: 'Bus Route Consolidation in Midday Hours',
    description: 'Buses BUS-02 and BUS-04 run with under 25% occupancy between 1 PM - 3 PM. Consolidating trips saves 180 L diesel monthly.',
    potentialSavingKg: 482,
    actionType: 'transport',
    confidence: 0.89,
    status: 'IN_PROGRESS',
  },
  {
    id: 'rec_03',
    targetType: 'user',
    targetName: 'Student Commuters',
    title: 'Shift Short Motorcycle Journeys (< 3 km) to Walking',
    description: 'Over 60% student motorcycle trips are under 3 km. Switching to walking earns 300+ Impact Points and cuts ~1.2 kg CO2e weekly per student.',
    potentialSavingKg: 150,
    actionType: 'transport',
    confidence: 0.96,
    status: 'NEW',
  },
];

export const CAMPUS_BUILDINGS_HOTSPOTS: CampusBuildingHotspot[] = [
  {
    id: 'bldg_01',
    name: 'CSE Tech Tower',
    code: 'CSE-MAIN',
    departmentName: 'Computer Science',
    co2eKgMonth: 12800,
    status: 'HIGH',
    latOffsetPct: 28,
    lngOffsetPct: 35,
    electricityKg: 10200,
    computingKg: 1800,
    acKg: 800,
  },
  {
    id: 'bldg_02',
    name: 'Civil Environmental Complex',
    code: 'CIVIL-BLK',
    departmentName: 'Civil Engineering',
    co2eKgMonth: 11200,
    status: 'MODERATE',
    latOffsetPct: 52,
    lngOffsetPct: 22,
    electricityKg: 8400,
    computingKg: 1200,
    acKg: 1600,
  },
  {
    id: 'bldg_03',
    name: 'E&TC Innovation Hub',
    code: 'ETC-HUB',
    departmentName: 'E&TC',
    co2eKgMonth: 12400,
    status: 'HIGH',
    latOffsetPct: 40,
    lngOffsetPct: 65,
    electricityKg: 9100,
    computingKg: 2100,
    acKg: 1200,
  },
  {
    id: 'bldg_04',
    name: 'Central Library & Green Learning Commons',
    code: 'LIB-CENTRAL',
    departmentName: 'Central Campus',
    co2eKgMonth: 4200,
    status: 'LOW',
    latOffsetPct: 70,
    lngOffsetPct: 50,
    electricityKg: 3500,
    computingKg: 400,
    acKg: 300,
  },
  {
    id: 'bldg_05',
    name: 'Hostel Mess & Food Court',
    code: 'MESS-MAIN',
    departmentName: 'Student Services',
    co2eKgMonth: 8600,
    status: 'MODERATE',
    latOffsetPct: 82,
    lngOffsetPct: 78,
    electricityKg: 4200,
    computingKg: 100,
    acKg: 4300,
  },
];
